# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remindme < Formula
  desc "Type less. Remember more. A simple terminal-based personal memory."
  homepage "https://github.com/aligunesv/remindme"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aligunesv/remindme/releases/download/v1.0.4/remindme_Darwin_x86_64.tar.gz"
      sha256 "703f712bd8d16b63ccecde2af15b6d0b62dbbc6be3690e3a433ff4a2309d90ae"

      define_method(:install) do
        bin.install "remindme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aligunesv/remindme/releases/download/v1.0.4/remindme_Darwin_arm64.tar.gz"
      sha256 "ded4f5320216bf19d30c880b511e1f971b2cfb68ac515deab32442b0d1e9b2ad"

      define_method(:install) do
        bin.install "remindme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aligunesv/remindme/releases/download/v1.0.4/remindme_Linux_x86_64.tar.gz"
      sha256 "7892a4212dd5103a369d6be7fde5dc5d2392214d1836957bd782212aae063531"
      define_method(:install) do
        bin.install "remindme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aligunesv/remindme/releases/download/v1.0.4/remindme_Linux_arm64.tar.gz"
      sha256 "61dc782c971123f55dabe7321eaf3e0f33955a9948e7592db22eb134d31c01fb"
      define_method(:install) do
        bin.install "remindme"
      end
    end
  end
end
